### ISSUE TITLE
Add simultaneous info for other attributes

### ISSUE THREAD

**Issue by chopchop505** [ProminentEdge/ES-simultaneous-update#4]
Great work thus far!
Now with this code and testing in place, does it make sense to calculate simultaneous comparisons by other attributes, such as battalion, first_due, etc.  This would be far more powerful for larger departments.

I'm thinking something like:
```
simultaneous: {
   department: {
      in_progress: 2,
      overlapping: 4,
   },
   first_due: {
      in_progress: 1,
      overlapping: 1
   },
  response_zone: {
     in_progress: 1,
     overlapping: 1
   }
  ....
}
```

At a minimum, I think first_due, response_zone, battalion, and census tracts.

**Comment by andersonad** [comment]
Agreed, will think about implementation for a bit and then move forward. We don't always have these attributes for a given department. The only other risk is that this requires pulling down those source fields with the query, which will increase the memory footprint by 2-2.5x. Not too bad now, but might get hairy in the future.

**Comment by chopchop505** [comment]
Sounds good.
For departments where we don't collect the attributes (or for a given incident where the field doesn't exist) - we would need to gracefully skip or handle. 

It probably's more efficient to make ES to do the grouping/aggregation, instead of doing it in memory.  

I would try the processing as a single job/script for now.  Once we hit memory constraints, we can start distributing the job. 

Here's some rough ideas on how we can scale up the job.
Worker nodes/jobs is just a concept of how we can break the processing in independent chunks.  

- run 1 query per department (give me all incidents, group/sort by first due & open date, group/sort by response zone & open date).  The response from ES will be huge, and the worker node will need to fit everything in memory.  We would have n worker nodes/jobs, where n is number of fire departments. 
The naive approach but also simplest.  

- run multiple queries per department (1. give me all incidents, group/sort by first due & open date, 2.  give me all incidents, group/sort by response zone & open date).  The response(s) from ES will be smaller, and memory requirements would be smaller.  We would have n*m worker nodes/jobs, where m is n number of fields we are grouping by.

**Comment by andersonad** [comment]
In light of Delaware, OH request, further delineate the category of the incidents (This type of calculation cannot be dynamically filtered otherwise) This will allow departments to examine load with respect to fire/ems calls as well in the event they cross-staff apparatus and have to make personnel trade-offs between EMS and Fire apparatus availability.

```
simultaneous: {
   department: {
      in_progress: {
        total:2,
        fire:1,
        ems:1
        other:0
      },
      overlapping: {
        total:4,
        fire:1,
        ems:2,
        other:1
   },
   first_due: {
      in_progress: {
        total:1
        ...},
      overlapping: {
        total:1
        ...},
   },
  response_zone: {
     in_progress: {
       total:1,
       ...},
     overlapping: {
       total:1,
       ...},
   }
  ....
   }
```
